trigger:
- none

pool:
  vmImage: ubuntu-latest
variables:
- group: NIRMAL_SCA

steps:
  - checkout: self
    fetchDepth: 0

  - task: BlackDuckSecurityScan@2
    displayName: 'Polaris SCA (Package + Signature)'
    inputs:
      POLARIS_SERVER_URL: $(POLARIS_SERVER_URL)
      POLARIS_ACCESS_TOKEN: $(POLARIS_ACCESS_TOKEN)

      # Run SCA; add the SCA test type below to include Signature analysis too
      POLARIS_ASSESSMENT_TYPES: 'SCA'
      POLARIS_TEST_SCA_TYPE: 'SCA-SIGNATURE,SCA-PACKAGE'

      # Optional quality-of-life settings
      POLARIS_APPLICATION_NAME: quickstart-$(Build.Repository.Name)
      POLARIS_PRCOMMENT_ENABLED: true
      POLARIS_REPORTS_SARIF_CREATE: true
      AZURE_TOKEN: $(System.AccessToken)
      MARK_BUILD_STATUS: 'SucceededWithIssues'
      INCLUDE_DIAGNOSTICS: true