trigger:
- none

pool:
  vmImage: ubuntu-latest
variables:
- group: NIRMAL_SCA
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
  displayName: 'Install Java'
- bash: |
    mvn --version
    java -version


- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'blackducksca'
    blackduckScaUrl: '$(POLARIS_SERVER_URL)'
    blackduckScaToken: '$(POLARIS_ACCESS_TOKEN)'
    blackduckScaWaitForScan: false
    detectArgs: '--detect.project.name=Merganser --detect.project.version.name=main --detect.project.versionphase=DEVELOPMENT --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING --detect.excluded.detector.types=GIT'